eureka:
  instance:
    prefer-ip-address: false
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    client:
      clientId: product-service
      clientSecret: password
      accessTokenUri: http://localhost:8100/uaa/oauth/token
      userAuthorizationUri: http://localhost:8100/uaa/oauth/authorize
      grant-type: client_credentials
#      scope: role_user,role_admin
