eureka:
  instance:
    prefer-ip-address: false
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    client:
      clientId: product-service
      clientSecret: password
      accessTokenUri: http://localhost:8100/uaa/oauth/token
#      grant-type: client_credentials
#      scope: read,write
feign:
  hystrix:
    enabled: true
