eureka:
  instance:
    prefer-ip-address: false
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/
security:
  oauth2:
    client:
      clientId: report-service
      clientSecret: password
      accessTokenUri: http://oauth-service:8100/uaa/oauth/token
      grant-type: client_credentials
#      scope: role_user,role_admin
