server:
  servlet:
    context-path: /report
  port: 8300
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8000/uaa/oauth/check_token
      user-info-uri: http://localhost:8000/uaa/oauth/current
resource-id: report
