server:
  servlet:
    context-path: /uaa
  port: 8100
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/oauth2
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    driver-class-name: org.mariadb.jdbc.Driver
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
check-user-scopes: false
signing-key: ewjk@837@$#^.8$
