zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    oauth-service:
      serviceId: oauth-service
      path: /oauth/** #path that will be intercepted
      url: oauth-service #which url the request will e mapped to
      stripPrefix: false #if zuul should replace the "/uaa/" segment
      sensitiveHeaders:
server:
  port: 8000
management:
  endpoints:
    exposure:
      include: "*"
  endpoint:
    health:
      show-details: always
